### PR TITLE
Payload Optical Schematic Updates

### PR DESCRIPTION
**Pull request by vogeldylan**
Updates to the payload schematics, some initial documentation (sorry, forgot to put on separate branch).

### CODE REVIEW

**Comment by vogeldylan** [comment]
@brunofalmeida pls check that I haven't done anything exceedingly dumb.

**Comment by brunofalmeida** [comment]
I thought we weren't putting docs together with development repos?

**Comment by vogeldylan** [comment]
I'm open to moving these docs around (i.e. to the documentation repository). Mostly just goofed and included them with the pay updates because I started thinking about them.

What do you think? This would be Altium documentation/tutorials. Could be it's own section in the documentation repo.

**Comment by brunofalmeida** [comment]
I agree it should be in its own section in the documentation repo

**Comment by vogeldylan** [comment]
@brunofalmeida removed docs from here

**Comment by vogeldylan** [comment]
No conflicts with merge, brings payload up to date.

**Pull request merged**
